### ISSUE TITLE
Add option that allows to pre-allocate disk space during DB creation process

### ISSUE THREAD

**Issue by Lazin** [akumuli/Akumuli#140]
This can be done using fallocate linux syscall or posix_fallocate. There is a function Storage::new_database in storage2.cpp that is used to create volumes. Extra parameter to aku_create_database_ex that controls this behavior should be introduced.

**Comment by Leviathan1995** [comment]
@Lazin  Is the parameter `bool` type? and the size of pre-allocate equal volume_size.

**Comment by Lazin** [comment]
@Leviathan1995 yes. It could be `bool` and the function should preallocate all volumes in full. The `volume_size` parameter is a size of the volume in bytes.

**Comment by Leviathan1995** [comment]
But how to set this option? in config file ?

**Comment by Lazin** [comment]
I think it should be set in command line. When user invokes `./akumulid --create` the database files should be created without preallocation and if user invokes `./akumulid --create --allocate` (or something like this) the database files should be created and allocated.

**Comment by Leviathan1995** [comment]
`posix_fallocate` function need a file descriptor, but I can not find a valid file descriptor in these code.

**Comment by Lazin** [comment]
You can open the file after it was created here - https://github.com/akumuli/Akumuli/blob/master/libakumuli/storage2.cpp#L1007
When the `StorageEngine::FileStorage::create` method exits all files listed in `paths` array are already created. You can open each file listed in `paths` and allocate the disk space.

**Comment by Leviathan1995** [comment]
@Lazin This feature is already completed, and what low-difficulty features have to do?

**Comment by Lazin** [comment]
Yes, I forgot to close the issue.
