### ISSUE TITLE
Set meaningful number of CPU's in config

### ISSUE THREAD

**Issue by Lazin** [akumuli/Akumuli#171]
Command `akumulid --init` creates the default configuration file in the user's home directory. The content of the config file is hardcoded in the `akumulid/main.cpp`. As result, this config contains generic values, e.g. parameter TCP.pool_size is set to 1 always.
The better approach is to set TCP.pool_size to 0 and make the code interpret this value as an instruction to start as many threads as number of CPU's on the machine.

**Comment by Leviathan1995** [comment]
Hi  @Lazin , I am interesting in this project, and I want to join in. I already find how to modify `TCP.pool_size` and `UDP.pool_size` value, but I am not sure that where to make the code interpret this value, and whether to modify config file at the same time.

**Comment by Lazin** [comment]
Hi,
I think that you can modify this pieces of code: 
https://github.com/akumuli/Akumuli/blob/cd1843f9173a523e5795b5dba104c85c0c0d1e41/akumulid/tcp_server.cpp#L365 
https://github.com/akumuli/Akumuli/blob/0b1673a064275077594e2d4cde89b5e830e37fe1/akumulid/httpserver.cpp#L181
https://github.com/akumuli/Akumuli/blob/cd1843f9173a523e5795b5dba104c85c0c0d1e41/akumulid/udp_server.cpp#L174

These are the builder functions that creates the servers for different protocols. Each one of those functions pases the `nworkers` parameter directly. It is possible to check if `nworkers` is zero and replace it with some meaningful value if this is the case.

E.g. you can set `nworkers` to std::hardware_concurrency() or you can use some other scheme. I would like to set `nworkers` to 1 if number of CPUs is less or equal to 4 and if we have more CPUs, I would set `nworkers` to std::hardwared_concurrency()*0.75 for the TCP server and to std::hardwared_concurrency()*0.25 for the HTTP server. UDP server will be good with `nworkers = 1` in all cases (id doesn't benefit from hardware concurrency at all).

**Comment by Leviathan1995** [comment]
I found HTTP server do not have `nworkers_` parameter.

**Comment by Lazin** [comment]
Oh, sorry. I forgot that HTTP server spawns thread per connection. It ignores this parameter now.
