### ISSUE TITLE
Non-fixed size storage implementation?

### ISSUE THREAD

**Issue by sundbp** [akumuli/Akumuli#175]
Hi,

I've read most of the akumuli blog and have had a first browse of the source code and like what I see. For my use case (financial data) it doesn't make sense to keep the storage size fixed as in the current default FixedSizeStorage implementation - I'd need a never-delete and growing-over-time Storage implementation. It'd be ok to e.g. add 1 volume at a time pre-allocated once one start to get to the end of the current volume for example.

It looks to me the work involved is implementing a sibling class to FixedSizeStorage removing the fixed size logic and adding the increase-on-demand logic. And to add config info to select which storage version to use (defaulting to current behavior if not given).

Is that a line of enquiry you'd be willing to engage with in principal? I could probably write a first draft of some code for it as it's not much novelty given the code already in place.

Thanks!

**Comment by Lazin** [comment]
Hi,
It is possible to do this. Configuration can be the same. The resizable storage can be enabled by setting parameter `nvolumes` to 0. 

The challenging part is a volume metadata tracking. There is a MetaVolume class in the code. The object of this class stores current write position of each volume in the file. This file is fixed size. For the non-fixed size storage, this file should be resized or each volume should have some sort of header at the beginning.

Anyway, I can help you with the code if you will send me the pull request with these changes.

**Comment by sundbp** [comment]
Excellent. I'll try to find some time to work on it - no promises but it's at least likely to happen :)

**Comment by sundbp** [comment]
After a first look it looks to me like making the MetaVolume be variable size for the non-fixed size storage is natural and least intrusive change.

**Comment by Lazin** [comment]
Implemented in https://github.com/akumuli/Akumuli/pull/176
