### ISSUE TITLE
broken pipe error

### ISSUE THREAD

**Issue by ssathasivan** [akumuli/Akumuli#211]
We are testing akumuli  for a use cases of ours . We are collecting analog and digital signals from tools and are planning to use the data for health monitoring. A tool generates 8000 records per second . Each record contains 50 analog and 50  digital signals . We are using GoLang program that collects data for 1 second and send it to AKumuli . A single data sample looks like this

+50a0|50a1|50a2|50a3|50a4|50a5|50a6|50a7|50a8|50a9|50a10|50a11|50a12|50a13|50a14|50a15|50a16|50a17|50a18|50a19|50a20|50a21|50a22|50a23|50a24|50a25|50a26|50a27|50a28|50a29|50a30|50a31|50a32|50a33|50a34|50a35|50a36|50a37|50a38|50a39|50a40|50a41|50a42|50a43|50a44|50a45|50a46|50a47|50a48|50a49|50d0|50d1|50d2|50d3|50d4|50d5|50d6|50d7|50d8|50d9|50d10|50d11|50d12|50d13|50d14|50d15|50d16|50d17|50d18|50d19|50d20|50d21|50d22|50d23|50d24|50d25|50d26|50d27|50d28|50d29|50d30|50d31|50d32|50d33|50d34|50d35|50d36|50d37|50d38|50d39|50d40|50d41|50d42|50d43|50d44|50d45|50d46|50d47|50d48|50d49 tag=42253\r\n+20170909T120643.99126436\r\n*100\r\n:8829\r\n:5805\r\n:6424\r\n:5077\r\n:1173\r\n:447\r\n:1803\r\n:5797\r\n:4104\r\n:1039\r\n:5715\r\n:7780\r\n:5184\r\n:5005\r\n:1472\r\n:6054\r\n:1288\r\n:4721\r\n:5392\r\n:6169\r\n:1882\r\n:9619\r\n:8404\r\n:3820\r\n:9941\r\n:1471\r\n:8069\r\n:7170\r\n:6585\r\n:4713\r\n:4925\r\n:7408\r\n:3805\r\n:5710\r\n:1480\r\n:8777\r\n:1684\r\n:8057\r\n:194\r\n:627\r\n:195\r\n:132\r\n:8717\r\n:5699\r\n:9315\r\n:4834\r\n:7766\r\n:496\r\n:6676\r\n:5737\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n:0\r\n:1\r\n

We are sending such 8000 message at end of one second... However after sometime insertion fails with error - broken pipe

Any help is appreciated

**Comment by Lazin** [comment]
It looks like akumulid closes connection because of error. In this case it should send error message back to client in telnet fashion and close connection afterwards. So you can spawn a goroutine that reads from the same socket that you're using for writing. This goroutine will block until connection will be closed or error message will be send by akumulid.

You can also check the log file. The location of the log file is set in the config file.
The input that you've sent is correct.

**Comment by ssathasivan** [comment]
Will it be any good if we reduce the sample size

**Comment by Lazin** [comment]
I'm not sure about that, it's hard to guess. Can you publish your log file somewhere or send it to me?

**Comment by ssathasivan** [comment]
Will do

**Comment by ssathasivan** [comment]
[akumuli.zip](https://github.com/akumuli/Akumuli/files/1289934/akumuli.zip)

I have attached the log files

**Comment by Lazin** [comment]
It fails because you're trying to write data points out of order. For each individual time-series all writes should be ordered by timestamp.

Out-of order writes will be implemented at some point. I'm working on it (this PR for example - https://github.com/akumuli/Akumuli/pull/205) but it's far from ready.

**Comment by ssathasivan** [comment]
Does this mean that the points should be written in increasing order of time , if so up to what precision

**Comment by Lazin** [comment]
Yes, this is the case. Two subsequent data-points can have the same timestamp, it wouldn't be an error. The error is triggered only if the timestamp of the next data-point is less than the timestamp of the previous one. This property is enforced only inside a series. Between series there is no such restriction, e.g. if you wrote data-point with timestamp 20171009T092800 into the first time-series you will be able to write data-point with timestamp 20161009T092800 into different time-series (if it doesn't already have a timestamp greater than this).

Akumuli supports nanosecond precision timestamps.

**Comment by ssathasivan** [comment]
Thanks we had some issues with our timestamp and this has been fixed
