### ISSUE TITLE
Late Write Support

### ISSUE THREAD

**Issue by akashgoswami** [akumuli/Akumuli#216]
Great Stuff and I have been playing around to feed some sensor data.

One of the problem is lazy writing is not supported (-DB late write). It will happen quite often that data from an IoT devices will arrive later than the last received value due to buffering / out of ordering in UDP. In that case, the write is failed. 

Is there anyway to circumvent this?

**Comment by Lazin** [comment]
Hi, nice to hear that! Late write support is a big problem. I'm working on it and it will be done eventually but not fast (e.g. this PR is a part of this project - https://github.com/akumuli/Akumuli/pull/205).
I can implement some workaround, for example, I can accept late write if it's not deep enough, if there are only a few data points with greater timestamps in this series. Can this be useful?

**Comment by akashgoswami** [comment]
I think a proper solution would be welcome as incoming timestamps may be quite late (such as device reboot or network disconnection). 

I've been able to find a way to put server side timestamps with nanosecond resolution, and with that the prototype works fine for now. However the timings are not real!

Unix socket support would be nice too!

**Comment by Lazin** [comment]
It's actually doesn't matter how late the data is. The only reason that matter is an amount of data that was already received. So it may work for device reboots. 

The other option is to buffer data on server side for some time period (e.g. 1 minute), order it by timestamp and send to Akumuli (I have done this once using [patience sort](https://en.wikipedia.org/wiki/Patience_sorting) algorithm). This algorithm will accept late writes if they are not too late (e.g. 10 minutes late). The main disadvantage is that the data will be available for queries with some delay.

Anyway, this is just an idea for temporary solution. The proper solution will take some time.

**Comment by Lazin** [comment]
BTW, why do you need Unix socket support?

**Comment by akashgoswami** [comment]
I have put an Nginx proxy in front of Akumuli and was hoping that Unix socket would improve the performance. However, the bottleneck is not the TCP at the moment so this could wait. It would be good improvement however for the future.
