### ISSUE TITLE
Question: Any way to remove time-series from the DB (so it became 'invisible')?

### ISSUE THREAD

**Issue by mmitkevich** [akumuli/Akumuli#222]
I've read in the FAQ that Akumuli doesn't support DELETEs (yet).
I wonder, if it is possible to manipulate sqlite database manually to remove old series from the db?

Consider I've got timeseries

PRICE symbol=MSFT containing 1 mln time points.

Now I've understood all this data is wrong and I want to replace it with another data.

So I need to delete old series metadata. I can live with that fact that b+tree nodes reserved for old data are not freed. But I can't live if I can't replace old series with new one: 

I could have db with 1000s of series. And just 1 mistake and I will need to recreate the whole database from scractch just to remove/replace a couple of wrong series.

Disclaimer: Yes, I try to use Akumuli as analytical database for stock price modelling

**Comment by Lazin** [comment]
You can manipulate sqlite database to do this. You need to delete a corresponding row from akumuli_series and akumuli_rescue_points tables. The ./akumulid app shouldn't be running during the process (or it will recreate the missing rows).

The query could be something like:

```sql
DELETE FROM akumuli_rescue_points
WHERE storage_id IN (SELECT storage_id FROM akumuli_series WHERE akumuli_series.series_id = 'net.sockstat.memory' and akumuli_series.keyslist = 'host=XPS type=tcp');

DELETE FROM akumuli_series WHERE akumuli_series.series_id = 'net.sockstat.memory' and akumuli_series.keyslist = 'host=XPS type=tcp';
```

tags should be sorted by name.
