### ISSUE TITLE
Unable to start docker version

### ISSUE THREAD

**Issue by Tezar** [akumuli/Akumuli#235]
After following instructions from https://hub.docker.com/r/akumuli/akumuli/ (with minor replacement of `akumuli/akumuli` to `akumuli/akumuli:master` in second command), container fails with following

```
WARNING: DB is not exist. creating
/root/akumuli.sh: line 32:    12 Illegal instruction     (core dumped) ${AKUMULID} --create
```

I have been so far unable to extract coredump (and after some googling, it may seem that there is chance that no has been created).
Is this known bug?

Version: 8fc6fbabf304e1dd9db69414e5fbdffac946c743 (current master)
OS: Archlinux  (Linux 4.14.12-1-ARCH) on VPS x86_64

**Comment by Lazin** [comment]
Hi! 
It looks like something new. Is there any files in the /Akumuli directory? It should contain the log file.

**Comment by Lazin** [comment]
BTW, what is the processor model of the machine?

**Comment by Tezar** [comment]
Unfortunately /Akumuli directory is empty.
As for processor, I can get specs only for virtual one:
```
cat /proc/cpuinfo | grep 'model name' | uniq
model name      : QEMU Virtual CPU version (cpu64-rhel6)
```

**Comment by Tezar** [comment]
Thanks for fast turnaround.
I tried with new version of image and I am still getting same error.

Is there anything I can do to provide more useful input?

**Comment by Lazin** [comment]
This looks like an illegal instruction error. That means that the image is being run on old hardware (for instance Intel Haswell CPU) but it's built for newer one (that particular build is tuned for Skylake and later).

**Comment by Lazin** [comment]
I'm going to build the image using the -march=generic in a separate docker repo. I hope this will solve the issue.

**Comment by Lazin** [comment]
Can you check image with tag 'generic' from [this repository](https://hub.docker.com/r/akumuli/test/)?

**Comment by Tezar** [comment]
Can confirm, test image works. DB created and api/stats returns something.

Do you have beerfund? :)

**Comment by Lazin** [comment]
OK, I need to figure out how to deploy this image. I'm thinking about separate docker repository for it (for instance akumuli/generic). No beerfund of any sort but issues, adoption, and other stuff like that is already a great help for the project. I really appreciate that, thank you!

**Comment by Lazin** [comment]
I added new build variant that builds Akumuli with -mtune=generic flag. It's available through 'generic' tag on DockerHub - https://hub.docker.com/r/akumuli/akumuli/
