### ISSUE TITLE
Possible buffer corruption in UDP receive parser

### ISSUE THREAD

**Issue by dmitrios** [akumuli/Akumuli#243]
**Description:** 
sending UDP to Akumuli in different packet sizes. 
**Symptoms:** 
exacly same content sent via TCP to Akumuli works fine. The UDP packet size from smallest to largest results in the same error. The content of buffer shown in the Akumuli log is corrupt (shows fragment of previous metric)
**Error in akumuli.log:** 
2018-01-29 21:55:53,761 UdpServer [ERROR] unexpected parameter id format - 
 `+innodb_metrics_ibuf_merges_cntr_value alias+innodb_metrics_ibuf_size_cntr_value alias=mysqldb collector=mysql-aku-aaaa-6b8f589f6d-2ll28 host=mysql01-mysql namespace=default pod=mysql-aku-sonar-6b8f589f6d-2ll28 Subsystem=change_buffer\n:1517256452334752200\n*1`
Note that that fragment is incorrect and not present in UDP packet:
`+innodb_metrics_ibuf_merges_cntr_value alias+innodb_metrics_ibuf_merges_cntr_value alias+`
Environment: k8s 1.9.2, same occurs on Docker deployment as well. Did not test without containers, so problem may be the same there too.

Repro: 
1. Send multiple metric types in the same packet va UDP  
2. sudo tcpdump -i cni0 -n udp port 8383 -X
3. Check akumuli logs.

**UDP : (tcpdump -i cni0 -n udp -X)**

The udp traffic  shows the content is correct:
15:53:48.478919 IP 10.244.0.147.42691 > 10.244.0.125.8383: UDP, length 2668
	0x0000:  4500 0a88 41a5 0000 3f11 18c9 0af4 0093  E...A...?.......
	0x0010:  0af4 007d a6c3 20bf 0a74 217d 2b69 6e6e  ...}.....t!}+inn
	0x0020:  6f64 625f 6d65 7472 6963 735f 696e 6e6f  odb_metrics_inno
	0x0030:  6462 5f72 776c 6f63 6b5f 785f 7370 696e  db_rwlock_x_spin
	0x0040:  5f77 6169 7473 5f63 6e74 725f 7661 6c75  _waits_cntr_valu
	0x0050:  6520 616c 6961 733d 6d79 7371 6c64 6220  e.alias=mysqldb.
	0x0060:  636f 6c6c 6563 746f 723d 6d79 7371 6c2d  collector=mysql-
	0x0070:  616b 752d 736f 6e61 722d 3662 3866 3538  aku-sonar-6b8f58
	0x0080:  3966 3664 2d6e 746a 7071 2068 6f73 743d  9f6d-ntjpq.host=
	0x0090:  6d79 7371 6c30 312d 6d79 7371 6c20 6e61  mysql01-mysql.na
	0x00a0:  6d65 7370 6163 653d 6465 6661 756c 7420  mespace=default.
	0x00b0:  706f 643d 6d79 7371 6c2d 616b 752d 736f  pod=mysql-aku-so
	0x00c0:  6e61 722d 3662 3866 3538 3966 3664 2d6e  nar-6b8f589f6d-n
	0x00d0:  746a 7071 2053 7562 7379 7374 656d 3d73  tjpq.Subsystem=s
	0x00e0:  6572 7665 720d 0a3a 3135 3137 3237 3030  erver..:15172700
	0x00f0:  3238 3430 3832 3737 3730 300d 0a2a 310d  28408277700..*1.
	0x0100:  0a2b 300d 0a2b 696e 6e6f 6462 5f6d 6574  .+0..+innodb_met
	0x0110:  7269 6373 5f69 6e6e 6f64 625f 7277 6c6f  rics_innodb_rwlo
	0x0120:  636b 5f73 785f 7370 696e 5f77 6169 7473  ck_sx_spin_waits
	0x0130:  5f63 6e74 725f 7661 6c75 6520 616c 6961  _cntr_value.alia
	0x0140:  733d 6d79 7371 6c64 6220 636f 6c6c 6563  s=mysqldb.collec
	0x0150:  746f 723d 6d79 7371 6c2d 616b 752d 736f  tor=mysql-aku-so
	0x0160:  6e61 722d 3662 3866 3538 3966 3664 2d6e  nar-6b8f589f6d-n
	0x0170:  746a 7071 2068 6f73 743d 6d79 7371 6c30  tjpq.host=mysql0
	0x0180:  312d 6d79 7371 6c20 6e61 6d65 7370 6163  1-mysql.namespac
	0x0190:  653d 6465 6661 756c 7420 706f 643d 6d79  e=default.pod=my
	0x01a0:  7371 6c2d 616b 752d 736f 6e61 722d 3662  sql-aku-sonar-6b
	0x01b0:  3866 3538 3966 3664 2d6e 746a 7071 2053  8f589f6d-ntjpq.S
	0x01c0:  7562 7379 7374 656d 3d73 6572 7665 720d  ubsystem=server.
	0x01d0:  0a3a 3135 3137 3237 3030 3238 3430 3832  .:15172700284082
	0x01e0:  3830 3830 300d 0a2a 310d 0a2b 300d 0a2b  80800..*1..+0..+
	0x01f0:  696e 6e6f 6462 5f6d 6574 7269 6373 5f69  innodb_metrics_i
	0x0200:  6e6e 6f64 625f 7277 6c6f 636b 5f73 5f73  nnodb_rwlock_s_s
	0x0210:  7069 6e5f 726f 756e 6473 5f63 6e74 725f  pin_rounds_cntr_
	0x0220:  7661 6c75 6520 616c 6961 733d 6d79 7371  value.alias=mysq
	0x0230:  6c64 6220 636f 6c6c 6563 746f 723d 6d79  ldb.collector=my
	0x0240:  7371 6c2d 616b 752d 736f 6e61 722d 3662  sql-aku-sonar-6b
	0x0250:  3866 3538 3966 3664 2d6e 746a 7071 2068  8f589f6d-ntjpq.h
	0x0260:  6f73 743d 6d79 7371 6c30 312d 6d79 7371  ost=mysql01-mysq
	0x0270:  6c20 6e61 6d65 7370 6163 653d 6465 6661  l.namespace=defa
	0x0280:  756c 7420 706f 643d 6d79 7371 6c2d 616b  ult.pod=mysql-ak
	0x0290:  752d 736f 6e61 722d 3662 3866 3538 3966  u-sonar-6b8f589f
	0x02a0:  3664 2d6e 746a 7071 2053 7562 7379 7374  6d-ntjpq.Subsyst
	0x02b0:  656d 3d73 6572 7665 720d 0a3a 3135 3137  em=server..:1517
	0x02c0:  3237 3030 3238 3430 3832 3833 3330 300d  270028408283300.
	0x02d0:  0a2a 310d 0a2b 360d 0a2b 696e 6e6f 6462  .*1..+6..+innodb
	0x02e0:  5f6d 6574 7269 6373 5f69 6e6e 6f64 625f  _metrics_innodb_
	0x02f0:  7277 6c6f 636b 5f78 5f73 7069 6e5f 726f  rwlock_x_spin_ro
	0x0300:  756e 6473 5f63 6e74 725f 7661 6c75 6520  unds_cntr_value.
	0x0310:  616c 6961 733d 6d79 7371 6c64 6220 636f  alias=mysqldb.co
	0x0320:  6c6c 6563 746f 723d 6d79 7371 6c2d 616b  llector=mysql-ak
	0x0330:  752d 736f 6e61 722d 3662 3866 3538 3966  u-sonar-6b8f589f
	0x0340:  3664 2d6e 746a 7071 2068 6f73 743d 6d79  6d-ntjpq.host=my
	0x0350:  7371 6c30 312d 6d79 7371 6c20 6e61 6d65  sql01-mysql.name
	0x0360:  7370 6163 653d 6465 6661 756c 7420 706f  space=default.po
	0x0370:  643d 6d79 7371 6c2d 616b 752d 736f 6e61  d=mysql-aku-sona
	0x0380:  722d 3662 3866 3538 3966 3664 2d6e 746a  r-6b8f589f6d-ntj
	0x0390:  7071 2053 7562 7379 7374 656d 3d73 6572  pq.Subsystem=ser
	0x03a0:  7665 720d 0a3a 3135 3137 3237 3030 3238  ver..:1517270028
	0x03b0:  3430 3832 3835 3730 300d 0a2a 310d 0a2b  408285700..*1..+
	0x03c0:  310d 0a2b 696e 6e6f 6462 5f6d 6574 7269  1..+innodb_metri
	0x03d0:  6373 5f69 6e6e 6f64 625f 7277 6c6f 636b  cs_innodb_rwlock
	0x03e0:  5f73 785f 7370 696e 5f72 6f75 6e64 735f  _sx_spin_rounds_
	0x03f0:  636e 7472 5f76 616c 7565 2061 6c69 6173  cntr_value.alias
	0x0400:  3d6d 7973 716c 6462 2063 6f6c 6c65 6374  =mysqldb.collect
	0x0410:  6f72 3d6d 7973 716c 2d61 6b75 2d73 6f6e  or=mysql-aku-son
	0x0420:  6172 2d36 6238 6635 3839 6636 642d 6e74  ar-6b8f589f6d-nt
	0x0430:  6a70 7120 686f 7374 3d6d 7973 716c 3031  jpq.host=mysql01
	0x0440:  2d6d 7973 716c 206e 616d 6573 7061 6365  -mysql.namespace
	0x0450:  3d64 6566 6175 6c74 2070 6f64 3d6d 7973  =default.pod=mys
	0x0460:  716c 2d61 6b75 2d73 6f6e 6172 2d36 6238  ql-aku-sonar-6b8
	0x0470:  6635 3839 6636 642d 6e74 6a70 7120 5375  f589f6d-ntjpq.Su
	0x0480:  6273 7973 7465 6d3d 7365 7276 6572 0d0a  bsystem=server..
	0x0490:  3a31 3531 3732 3730 3032 3834 3038 3238  :151727002840828
	0x04a0:  3830 3030 0d0a 2a31 0d0a 2b30 0d0a 2b69  8000..*1..+0..+i
	0x04b0:  6e6e 6f64 625f 6d65 7472 6963 735f 696e  nnodb_metrics_in
	0x04c0:  6e6f 6462 5f72 776c 6f63 6b5f 735f 6f73  nodb_rwlock_s_os
	0x04d0:  5f77 6169 7473 5f63 6e74 725f 7661 6c75  _waits_cntr_valu
	0x04e0:  6520 616c 6961 733d 6d79 7371 6c64 6220  e.alias=mysqldb.
	0x04f0:  636f 6c6c 6563 746f 723d 6d79 7371 6c2d  collector=mysql-
	0x0500:  616b 752d 736f 6e61 722d 3662 3866 3538  aku-sonar-6b8f58
	0x0510:  3966 3664 2d6e 746a 7071 2068 6f73 743d  9f6d-ntjpq.host=
	0x0520:  6d79 7371 6c30 312d 6d79 7371 6c20 6e61  mysql01-mysql.na
	0x0530:  6d65 7370 6163 653d 6465 6661 756c 7420  mespace=default.
	0x0540:  706f 643d 6d79 7371 6c2d 616b 752d 736f  pod=mysql-aku-so
	0x0550:  6e61 722d 3662 3866 3538 3966 3664 2d6e  nar-6b8f589f6d-n
	0x0560:  746a 7071 2053 7562 7379 7374 656d 3d73  tjpq.Subsystem=s
	0x0570:  6572 7665 720d 0a3a 3135 3137 3237 3030  erver..:15172700
	0x0580:  3238 3430 3832 3931 3330 300d 0a2a 310d  28408291300..*1.
	0x0590:  0a2b 330d 0a2b 696e 6e6f 6462 5f6d 6574  .+3..+innodb_met
	0x05a0:  7269 6373 5f69 6e6e 6f64 625f 7277 6c6f  rics_innodb_rwlo
	0x05b0:  636b 5f78 5f6f 735f 7761 6974 735f 636e  ck_x_os_waits_cn
	0x05c0:  7472 5f76 616c 7565 2061 6c69 6173 3d6d  tr_value.alias=m
	0x05d0:  7973 716c 6462 2063 6f6c 6c65 6374 6f72  ysqldb.collector
	0x05e0:  3d6d 7973 716c 2d61 6b75 2d73 6f6e 6172  =mysql-aku-sonar
	0x05f0:  2d36 6238 6635 3839 6636 642d 6e74 6a70  -6b8f589f6d-ntjp
	0x0600:  7120 686f 7374 3d6d 7973 716c 3031 2d6d  q.host=mysql01-m
	0x0610:  7973 716c 206e 616d 6573 7061 6365 3d64  ysql.namespace=d
	0x0620:  6566 6175 6c74 2070 6f64 3d6d 7973 716c  efault.pod=mysql
	0x0630:  2d61 6b75 2d73 6f6e 6172 2d36 6238 6635  -aku-sonar-6b8f5
	0x0640:  3839 6636 642d 6e74 6a70 7120 5375 6273  89f6d-ntjpq.Subs
	0x0650:  7973 7465 6d3d 7365 7276 6572 0d0a 3a31  ystem=server..:1
	0x0660:  3531 3732 3730 3032 3834 3038 3239 3338  5172700284082938
	0x0670:  3030 0d0a 2a31 0d0a 2b31 0d0a 2b69 6e6e  00..*1..+1..+inn
	0x0680:  6f64 625f 6d65 7472 6963 735f 696e 6e6f  odb_metrics_inno
	0x0690:  6462 5f72 776c 6f63 6b5f 7378 5f6f 735f  db_rwlock_sx_os_
	0x06a0:  7761 6974 735f 636e 7472 5f76 616c 7565  waits_cntr_value
	0x06b0:  2061 6c69 6173 3d6d 7973 716c 6462 2063  .alias=mysqldb.c
	0x06c0:  6f6c 6c65 6374 6f72 3d6d 7973 716c 2d61  ollector=mysql-a
	0x06d0:  6b75 2d73 6f6e 6172 2d36 6238 6635 3839  ku-sonar-6b8f589
	0x06e0:  6636 642d 6e74 6a70 7120 686f 7374 3d6d  f6d-ntjpq.host=m
	0x06f0:  7973 716c 3031 2d6d 7973 716c 206e 616d  ysql01-mysql.nam
	0x0700:  6573 7061 6365 3d64 6566 6175 6c74 2070  espace=default.p
	0x0710:  6f64 3d6d 7973 716c 2d61 6b75 2d73 6f6e  od=mysql-aku-son
	0x0720:  6172 2d36 6238 6635 3839 6636 642d 6e74  ar-6b8f589f6d-nt
	0x0730:  6a70 7120 5375 6273 7973 7465 6d3d 7365  jpq.Subsystem=se
	0x0740:  7276 6572 0d0a 3a31 3531 3732 3730 3032  rver..:151727002
	0x0750:  3834 3038 3239 3631 3030 0d0a 2a31 0d0a  8408296100..*1..
	0x0760:  2b30 0d0a 2b69 6e6e 6f64 625f 6d65 7472  +0..+innodb_metr
	0x0770:  6963 735f 646d 6c5f 696e 7365 7274 735f  ics_dml_inserts_
	0x0780:  636e 7472 5f76 616c 7565 2061 6c69 6173  cntr_value.alias
	0x0790:  3d6d 7973 716c 6462 2063 6f6c 6c65 6374  =mysqldb.collect
	0x07a0:  6f72 3d6d 7973 716c 2d61 6b75 2d73 6f6e  or=mysql-aku-son
	0x07b0:  6172 2d36 6238 6635 3839 6636 642d 6e74  ar-6b8f589f6d-nt
	0x07c0:  6a70 7120 686f 7374 3d6d 7973 716c 3031  jpq.host=mysql01
	0x07d0:  2d6d 7973 716c 206e 616d 6573 7061 6365  -mysql.namespace
	0x07e0:  3d64 6566 6175 6c74 2070 6f64 3d6d 7973  =default.pod=mys
	0x07f0:  716c 2d61 6b75 2d73 6f6e 6172 2d36 6238  ql-aku-sonar-6b8
	0x0800:  6635 3839 6636 642d 6e74 6a70 7120 5375  f589f6d-ntjpq.Su
	0x0810:  6273 7973 7465 6d3d 646d 6c0d 0a3a 3135  bsystem=dml..:15
	0x0820:  3137 3237 3030 3238 3430 3832 3938 3530  1727002840829850
	0x0830:  300d 0a2a 310d 0a2b 3232 0d0a 2b69 6e6e  0..*1..+22..+inn
	0x0840:  6f64 625f 6d65 7472 6963 735f 646d 6c5f  odb_metrics_dml_
	0x0850:  6465 6c65 7465 735f 636e 7472 5f76 616c  deletes_cntr_val
	0x0860:  7565 2061 6c69 6173 3d6d 7973 716c 6462  ue.alias=mysqldb
	0x0870:  2063 6f6c 6c65 6374 6f72 3d6d 7973 716c  .collector=mysql
	0x0880:  2d61 6b75 2d73 6f6e 6172 2d36 6238 6635  -aku-sonar-6b8f5
	0x0890:  3839 6636 642d 6e74 6a70 7120 686f 7374  89f6d-ntjpq.host
	0x08a0:  3d6d 7973 716c 3031 2d6d 7973 716c 206e  =mysql01-mysql.n
	0x08b0:  616d 6573 7061 6365 3d64 6566 6175 6c74  amespace=default
	0x08c0:  2070 6f64 3d6d 7973 716c 2d61 6b75 2d73  .pod=mysql-aku-s
	0x08d0:  6f6e 6172 2d36 6238 6635 3839 6636 642d  onar-6b8f589f6d-
	0x08e0:  6e74 6a70 7120 5375 6273 7973 7465 6d3d  ntjpq.Subsystem=
	0x08f0:  646d 6c0d 0a3a 3135 3137 3237 3030 3238  dml..:1517270028
	0x0900:  3430 3833 3031 3630 300d 0a2a 310d 0a2b  408301600..*1..+
	0x0910:  300d 0a2b 696e 6e6f 6462 5f6d 6574 7269  0..+innodb_metri
	0x0920:  6373 5f64 6d6c 5f75 7064 6174 6573 5f63  cs_dml_updates_c
	0x0930:  6e74 725f 7661 6c75 6520 616c 6961 733d  ntr_value.alias=
	0x0940:  6d79 7371 6c64 6220 636f 6c6c 6563 746f  mysqldb.collecto
	0x0950:  723d 6d79 7371 6c2d 616b 752d 736f 6e61  r=mysql-aku-sona
	0x0960:  722d 3662 3866 3538 3966 3664 2d6e 746a  r-6b8f589f6d-ntj
	0x0970:  7071 2068 6f73 743d 6d79 7371 6c30 312d  pq.host=mysql01-
	0x0980:  6d79 7371 6c20 6e61 6d65 7370 6163 653d  mysql.namespace=
	0x0990:  6465 6661 756c 7420 706f 643d 6d79 7371  default.pod=mysq
	0x09a0:  6c2d 616b 752d 736f 6e61 722d 3662 3866  l-aku-sonar-6b8f
	0x09b0:  3538 3966 3664 2d6e 746a 7071 2053 7562  589f6d-ntjpq.Sub
	0x09c0:  7379 7374 656d 3d64 6d6c 0d0a 3a31 3531  system=dml..:151
	0x09d0:  3732 3730 3032 3834 3038 3330 3430 3030  7270028408304000
	0x09e0:  0d0a 2a31 0d0a 2b30 0d0a 2b69 6e6e 6f64  ..*1..+0..+innod
	0x09f0:  625f 6d65 7472 6963 735f 736f 6e61 725f  b_metrics_sonar_
	0x0a00:  7363 7261 7065 5f64 7572 6174 696f 6e5f  scrape_duration_
	0x0a10:  6d69 6c6c 6973 6563 6f6e 6473 2061 6c69  milliseconds.ali
	0x0a20:  6173 3d6d 7973 716c 6462 2063 6f6c 6c65  as=mysqldb.colle
	0x0a30:  6374 6f72 3d6d 7973 716c 2d61 6b75 2d73  ctor=mysql-aku-s
	0x0a40:  6f6e 6172 2d36 6238 6635 3839 6636 642d  onar-6b8f589f6d-
	0x0a50:  6e74 6a70 7120 686f 7374 3d6d 7973 716c  ntjpq.host=mysql
	0x0a60:  3031 2d6d 7973 716c 0d0a 3a31 3531 3732  01-mysql..:15172
	0x0a70:  3730 3032 3834 3038 3330 3634 3030 0d0a  70028408306400..
	0x0a80:  2a31 0d0a 2b31 0d0a                      *1..+1..

**Comment by Lazin** [comment]
I think that I fixed it. Can you check the image from this - repohttps://hub.docker.com/r/akumuli/test/

**Comment by dmitrios** [comment]
Tested with akumuli/test:skylake Same error:
'root@aku-akumuli-cd9bcffc7-hz59t:/# cat /Akumuli/logs/akumuli.log | grep ERROR
2018-01-31 00:26:36,710 UdpServer [ERROR] invalid series name format - +innodb_metrics_ibuf_merges_discard_insert_cntr_value +innodb_metrics_innodb_rwlock_x_spin_waits_cntr_value alias=mysqldb collector=mysql-aku-sonar-6b8f589f6d-ntjpq host=mysql01-mysql namespace=default pod=mysql-aku-sonar-6b8f589f6d-ntjpq Subsystem=server\r\n:1517358396660377100\r\n*1\r'

**Comment by Lazin** [comment]
I think it should work now. I was able to reproduce and pinpoint the issue. The image is akumuli/test.

**Comment by dmitrios** [comment]
Fixed - tested with akumuli/test:skylake

**Comment by Lazin** [comment]
Fixed in #244
