### ISSUE TITLE
libakumuli.so shared library does not support preload

### ISSUE THREAD

**Issue by dmitrios** [akumuli/Akumuli#245]
Using libakumuli ( as standalone shared library ) does not support preload.
Repro:
export LD_PRELOAD="/home/path/libakumuli.so"
Error:
wc: symbol lookup error: /home/user/Projects/akumuli/build/libakumuli/libakumuli.so: undefined symbol: pthread_create
Comments:
I suspect that either  -fPIC  -ldl -shared or -pthread options are not set and library cannot be loaded. As result dlopen(libfile,2) does not work correctly.

**Comment by Lazin** [comment]
I created PR #246 that should fix the issue (once the CI checks pass).

**Comment by dmitrios** [comment]
PR #246 works for me also.
