### ISSUE TITLE
Performance comparison with Prometheus

### ISSUE THREAD

**Issue by wh0-am-i** [akumuli/Akumuli#253]
Prometheus 2.0 has brought lot of improvements to its storage layer. https://coreos.com/blog/prometheus-2.0-storage-layer-optimization . Have you done any performance comparison to Prometheus?

**Comment by Lazin** [comment]
It looks like the article doesn't have any benchmarks results to compare with.

**Comment by weeeeeeeeeee** [comment]
Thanks for the quick response. I found that Prometheus has a benchmark tool https://github.com/prometheus/prombench

There are some numbers mentioned in https://fabxc.org/tsdb/#benchmarking . The storage engine is here: https://github.com/prometheus/tsdb

**Comment by Lazin** [comment]
Citing the article - "it is synthetic and thus not worth much beyond a good first impression". I can't benchmark against all existing databases, it's simply too time-consuming. But I have some nice [benchmark results here](http://akumuli.org/akumuli/2017/03/10/benchmark2/).

**Comment by weeeeeeeeeee** [comment]
I understand! Though given the hype of Prometheus in the container / Kubernetes space,  it will be interesting to see if Akumuli can be used as a storage engine for Prometheus. Like you said before, there are no performance ceiling for C++ based programs compared to GC-ed languages.

Regarding your article, those numbers are a year old. Are things supposed to be any better now?

**Comment by Lazin** [comment]
Prometheus has remote read/write feature and there is a lot of integrations with other time-series databases. I'm considering writing integration but the protocol is not finalized yet. Akumuli supports OpenTSDB telnet interface so it can be used with netdata collector that can monitor containers.

The numbers in the article should hold. I'm checking performance periodically.

**Comment by wh0-am-i** [comment]
The remote read/write feature seems to be mostly for long term storage. see here: https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

Does Akumuli support storing labels for time series and querying based on that?

What are your long terms plans for Akumuli, if you don't mind sharing? Do you use it for personal use? Are there any production users of Akumuli ?

**Comment by Lazin** [comment]
I'm going to improve the database further. The plans are mostly described in the README. The main challenge now is out of order write support. Also, I'm open to improving something if this something will make Akumuli more interesting for users. Talking about me, I'm using it in my closed source software. Also, I know about several companies that use Akumuli but I don't know a lot of details.
