### ISSUE TITLE
Query timeout when using csv format

### ISSUE THREAD

**Issue by dmitrios** [akumuli/Akumuli#265]
Consider the following query
`
{ "group-aggregate":
                          {
                          "metric": "processor_time",
                          "step": "1m",
                          "func": ["max","min"]
                          },
                          "range": { "from": "20180330T165816.8479803","to": "20180330T165916.8479803"},
                          "output": { "format": "csv","timestamp": "raw"  },
                          "limit" : "100",
                          "order-by":"series",
                          "apply":[] }
`
Steps to repro:
`
docker run --name aku -d -p 8181:8181 -p 8282:8282 -p 8383:8383/udp -p 4242:4242 \
       -v /Akumuli -e nvolumes='1' \
       -e volume_size='1GB' akumuli/akumuli:skylake 
`
Expected result: non-empty dataset.
Actual result: timeout

Same environment, using older version of Akumuli:
`
docker run --name aku -d -p 8181:8181 -p 8282:8282 -p 8383:8383/udp -p 4242:4242 \
       -v /Akumuli -e nvolumes='1' \
       -e volume_size='1GB' akumuli/test:fix_signal_prop  
`
Expected result: non-empty dataset.
Actual result: non-empty dataset.

Is it correct to expect that new versions of Akumuli are backward compatible? Also, the current versioning for docker images violates best practices and does not allow rollback to last stable version. Consider something like:
akumuli/akumuli:0.2.4-skylake
akumuli/akumuli:0.2.3-skylake 

With current versioning everyone who uses Akumuli on Kubernetes in this scenario would have broken environment.

**Comment by Lazin** [comment]
Sorry for the inconvenience, I'm investigating it. 

> Is it correct to expect that new versions of Akumuli are backward compatible?

Yes, this is correct. I can only add something new. I'll add new endpoint if new query language will be introduced.

**Comment by dmitrios** [comment]
No worries. It would be helpful if latest stable docker images ( before filter expressions were added) would be re-published with versioning guidelines (described above) followed. Having explicit versions helps to troubleshoot quickly and eliminates need to search for "test" images.

**Comment by Lazin** [comment]
I added `akumuli/akumuli:0.7.38-skylake` docker image.

**Comment by dmitrios** [comment]
The v0.7.38-skylake works fine. Thanks.

**Comment by dmitrios** [comment]
I could repro this bug with the original Docker image (akumuli/akumuli:skylake) while all other images, including 0.7.44 work fine.

**Comment by Lazin** [comment]
This is really interesting. It looks like I made a mistake. When I had been building this docker images I've used proper deb packages but I forget to update the configuration in docker directory. So, this PR - https://github.com/akumuli/Akumuli/pull/261/files is not applied and everything works. The containers with a version inside their tag don't log to stdout.

**Comment by dmitrios** [comment]
What is more interesting is this bug occurs only when using query with result in CSV format: running similar query at the same time in Grafana works. However, performance is noticeably slower, which may be caused by blocking IO when logging to stdout/stderr.

**Comment by Lazin** [comment]
I think that this issue can be fixed by redirecting all trace messages to the log file and using stdout only for error/info messages.

**Comment by dmitrios** [comment]
I think so too: traces only useful for troubleshooting logs and can be even disabled by default. For Docker images simplest way would be setting and reading environment variables for logging at deployment/startup to tweak right combination.

**Comment by Lazin** [comment]
I fixed the issue. It is possible to use 'log_level' variable to filter log messages now. Also, the default log level is WARN now (instead of ALL). Also, docker image tags now contain a version.

**Comment by dmitrios** [comment]
Cool. I have only spent 15min with akumuli/akumuli:0.7.45-skylake, looks good so far. Also, removing excessive logging likely reduced pod memory footprint on k8s: around 10Mb instead of 27Mb.

**Comment by dmitrios** [comment]
Also, there is another strange symptom: in Grafana v4 and v5 down sample interval generated by Akumuli plugin is 15s for Grafana interval is set to 6 hours. Not sure how plugin computes it (Grafana does auto-compute it) but as result very small step in group aggregate query returns lot of unnecessary data.

**Comment by Lazin** [comment]
If you haven't set the downsampling interval explicitly, the datasource plugin will use the the interval provided by Grafana. On my machine Grafana uses 15s sample interval for 3 hours range and 30s sample interval for 6 hours. Maybe your monitor have larger resolution?

**Comment by dmitrios** [comment]
It is not a resolution issue, also I use MacPro standard resolution.  It appears that setting down sample interval manually in Akumuli plugin query editor doe not have any effect. I see it with (Grafana v5, Safari) so it maybe plugin issue.

**Comment by Lazin** [comment]
That issue was fixed recently. Also, I've added an option to set an alias for the series.

**Comment by dmitrios** [comment]
Nope. It still exists.

**Comment by Lazin** [comment]
Checked once more. It looks like the interval can only be increased but not decreased.

**Comment by Lazin** [comment]
Can you point me, what parameters are you using and what is the git hash or version of the datasource?

**Comment by dmitrios** [comment]
https://github.com/akumuli/akumuli-datasource/commit/1df96d6acc96d9aa5f5c342ca9369b4b6cec6550 - cloned yesterday. I did run Grafana v5 dicker image with Safari.

**Comment by dmitrios** [comment]
Looks like it does work in Chrome, but not in Safari. I'll see if I can repro this later this week.

**Comment by Lazin** [comment]
OK, thanks for the clue. I'll try it in the Safari.

**Comment by dmitrios** [comment]
Safari actually has a few bugs, so I would not be surprised it is one of them. Another issue is with multi-value selection of template variable for repeat and tag for filtering. It appears that variable  has value 
`
{A}
`
intstead of
`
A
`
when multiple tag values like A,B are selected in the drop down. Thus, query in repeated graph fails.

**Comment by Lazin** [comment]
I fixed the multi-value selection. Safari issue is not yet fixed (have to install Safari first).

**Comment by Lazin** [comment]
Also, you can specify more than one value for the tag in `Tags` section now.

**Comment by dmitrios** [comment]
Cool. If you do not have Mac it would be difficult to test with Safari. I think if it works in Chrome it would be fine.
