### ISSUE TITLE
Ran: akumulid --init got: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by togo59** [akumuli/Akumuli#279]
Hi,
Centos 7.2
Linux db1.race.apps.l 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 13:12:24 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
Installation - no errors.
Ran: `akumulid --init` got: `Illegal instruction (core dumped)`
journalctl gives:
Jul 25 09:42:14 db1.race.apps.l kernel: traps: akumulid[24204] trap invalid opcode ip:452066 sp:7ffd8bbe1fb0 error:0 in akumulid[400000+92000]
Jul 25 09:42:14 db1.race.apps.l abrt-hook-ccpp[24205]: Process 24204 (akumulid) of user 1000 killed by SIGILL - dumping core
Jul 25 09:42:14 db1.race.apps.l abrt-server[24206]: Package 'akumuli' isn't signed with proper key
Jul 25 09:42:14 db1.race.apps.l abrt-server[24206]: 'post-create' on '/var/spool/abrt/ccpp-2018-07-25-09:42:14-24204' exited with 1
Jul 25 09:42:14 db1.race.apps.l abrt-server[24206]: Deleting problem directory '/var/spool/abrt/ccpp-2018-07-25-09:42:14-24204'

What did I do wrong?
See attached.
[akumuli-core-dumped.txt](https://github.com/akumuli/Akumuli/files/2227511/akumuli-core-dumped.txt)

**Comment by Lazin** [comment]
Hi,
The problem is that Akumuli packages are built using the skylake instruction set. Akumuli can work on older CPU's. You can use docker image with 'generic' tag (https://hub.docker.com/r/akumuli/akumuli/) or you can build it manually. To build it manually try this:

```
git clone https://github.com/akumuli/Akumuli
cd Akumuli
sh ./CI/prerequisites-centos7.sh
mkdir build; cd build
cmake .. -DCMAKE_BUILD_TYPE=ReleaseGen
make
```

if you need to build rpm package:

```
cpack -G RPM
```

**Comment by togo59** [comment]
Thank you. Built it manually as suggested. Now running. Seems fine.
