### ISSUE TITLE
Mean aggregation be at top or bottom of time period

### ISSUE THREAD

**Issue by dixonp1** [akumuli/Akumuli#282]
Maybe I'm doing it wrong, but when querying for mean group-aggregation of a series by time periods (1m, 1h, etc.), data points return with timestamps somewhere in the middle of the specified time period. For example, requesting hourly averages of the last 24-hrs data points return with timestamps of 3:24:27, 4:20:49, ..., would like to get averages at top or bottom of time period such that the mean of data points between 3:00 and 4:00 would return with timestamp 3:00 or 4:00

**Comment by Lazin** [comment]
Can you post your query here?

**Comment by dixonp1** [comment]
{
    "group-aggregate": {
        "metric": "temp",
        "step": "1h",
        "func": [
            "mean"
        ]
    },
    "range": {
        "from": "20181107T184508.085",
        "to": "20181108T184508.085"
    }
}

I'll get timestamps at 10:45:30, next would be 11:45:15. That's just grabbing the current timestamp and subtracting a day.

**Comment by Lazin** [comment]
It looks like it takes the timestamp of the first data-point inside the range. I'm going to fix this.

**Comment by dixonp1** [comment]
That's what I suspected too. When you do fix it, please let me know, I really like your program
