### ISSUE TITLE
Nanosecond resolution and compile options

### ISSUE THREAD

**Issue by JoelStienlet** [akumuli/Akumuli#291]
Hello,
I'm new to Akumuli, I've built it from source, and doing some tests I got some "-DB late write" replies.
After some investigation, I found that boost::posix_time::time_duration() in datetime.cpp in "from_iso_string()" returned incoherent values when giving nanosecond timestamps.
For example when sending: b'+test sensor=dummy\r\n+20190222T110923.602227\r\n+1234\r\n'
it returned: 00:00:40.765227000 : hours and minutes were gone...
I found that BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG was defined, and according to the documentation (https://www.boost.org/doc/libs/1_31_0/libs/date_time/doc/BuildInfo.html): " This alternative implementation may provide better performance and more compact memory usage for many applications that do not require nano-second resolutions. "
But I require at least milliseconds, so this portion of the code is required in my case.
I'm not sure the problem is BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG, I've not tested a compiled version where it is undefined yet.
But in any case (even If this is my error not defining the correct compile options) I think it would make sense to add a test to display this specific error in the logs, for example:
if (p != pend) {
#ifdef BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG
         Logger::msg(AKU_LOG_ERROR, "nanosecond resolution cannot be used when BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG is defined as a compiler option");
#endif
because the response "-DB late write" alone, without any further errors in the logs, got me confused when debugging this.

**Comment by JoelStienlet** [comment]
BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG is defined in "datetime.h", and contrarily to what I said above, it has to be defined to get nanosecond resolution. So Akumuli's code is correct, and this looks like a boost bug now.

**Comment by Lazin** [comment]
Thank you for reporting this.
What boost version are you using?

**Comment by JoelStienlet** [comment]
BOOST_LIB_VERSION is 1_66

**Comment by JoelStienlet** [comment]
I've been able to reproduce this in a small test: it seems that BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG should be defined before any boost include is made.
When asio is included before the define -> BUG.
When asio is included after the define -> this test works OK.
The source code of the test: (comment only one include of asio at the same time)

```
#include <iostream>
// BUG:
#include <boost/asio.hpp>

#define BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG
#include <boost/date_time/posix_time/posix_time.hpp>

// NOT buggy:
//#include <boost/asio.hpp>

int main(void)
{
 
boost::posix_time::time_duration::hour_type hour;
boost::posix_time::time_duration::min_type minute;
boost::posix_time::time_duration::sec_type second;
boost::posix_time::time_duration::fractional_seconds_type nanoseconds;
// 110328.861621
hour = 11;
minute = 03;
second = 28;
nanoseconds = 861621000;
    
boost::posix_time::time_duration time = boost::posix_time::time_duration(hour, minute, second, nanoseconds);
std::cerr << BOOST_LIB_VERSION << std::endl;
std::cout << hour<< " " << minute<< " " << second<< " " << nanoseconds << " result: " << time << std::endl;
    
return 0;    
}
```

**Comment by Lazin** [comment]
Oh boy! Thank you for sharing this! I'll try to come up with a fix. Here is the runnable paste - https://coliru.stacked-crooked.com/a/9ac3a2d2b8e00dd5

**Comment by Lazin** [comment]
First of all, thank you for spending your time to investigation. It's been a while since I wrote this so I had to dig a bit too.

BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG enables nanosecond timestamps. Without it boost-datetime uses 64 bit timestamps (boost::posix_time::ptime values) which allows to store timestamps with microsecond precision (the default). If this macro is defined it uses 96 bit ptime values that can represent nanoseconds.

The problem may occur when different translation units use `ptime` of different size. Maybe this is what happens in your example (asio uses datetime internally and it may (un)define that pre-processor definition). I've added extra checks and extra debug output and and ran the tests. Pretty sure that everything works as intended. The datetime.cpp is a part of the `libakumuli` library and asio is used in the `akumulid` application so there is no way this clash will occur.

I checked the `from_iso_string` function with the value you've provided and it returns correct output - 1550833763602227000ns. One thing that I've noticed is that GDB in Ubuntu 16.04 comes with the debugging helper for boost::posix_time::ptime. But this helper shows the wrong value. Probably it's built for 64-bit ptime values or outdated.

The 'late write' reply means that the last timestamp was smaller than its predecessor. Akumuli allows to use only increasing timestamps for any individual time-series. In other words, it's not possible to write to the past. If your test script does this Akumuli will return 'late write' error and drop connection. If this is not the case, than it's a bug and any information that will help me to reproduce it will be greatly appreciated!

**Comment by JoelStienlet** [comment]
Hello,
Thank you for the explanations and clarifications!
I still think there is a bug somewhere though. I'll copy-paste a small test code in python that will (hopefully) allow you to reproduce what I get.
I'm running fedora 29 with boost 1_66, gcc version 8.2.1
I just took a fresh "git clone", recompiled and reinstalled everything, I delete the database between two successive tests ("rm -rf" of database directory) and run "akumulid --create" to make a new empty one, so that there should really be no difference between tests.

```
#!/bin/env python3
# coding: utf-8

import sys
import subprocess
try:
    subprocess.run(['pyflakes-3', sys.argv[0] ], check=True);
except subprocess.CalledProcessError as err:
    print('ERROR: abord.');
    print(err);
    sys.exit(1);

import socket
import dateutil.parser

def wait_for_response(sock):
    try:
        data = sock.recv(100)
        print("reponse: (please also check Akumuli's logs)")
        print(data) # .decode('utf-8')
    except Exception as e:
        print("socket error recv: ", e)

# when data are received on the socket, it is an error, and I can also see this in the logs:
# 
#2019-02-23 16:47:40,615 tcp-session-0 [ERROR] /home/stienlet/Programmation/DataLogging/Akumuli/akumulid/protocolparser.cpp(551): Throw in function void Akumuli::RESPProtocolParser::worker()
#Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<Akumuli::DatabaseError> >
#std::exception::what: late write


def send_packet(sock, timestr):
    msg  = b'+test sensor=dummy\r\n'
    msg += b'+' + timestr + b'\r\n'
    msg += b'+1234\r\n'
    print(msg.decode('utf-8'))
    sock.send(msg)
    print("Packet sent.");
    wait_for_response(sock)

def check_packs(firstp, nextp):
    low  = dateutil.parser.parse(firstp)
    high = dateutil.parser.parse(nextp)
    if low > high:
        raise Exception('timestamps are supposed to be increasing!')
    
    
def main_fct():
    print("Test: send hand-crafted data to akumuli server");
    
    # should we trigger a bug, or simulate a nice case?
    trig_bug = True
    
    host = '127.0.0.1'
    port = 8282
    
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(2)   
    sock.connect((host, port))
    
    # A previous test has shown that, when some specific time values are sent in succession to akumuli, this generates a bug.
    # The folling packets are cut-pastes of some pathological values identified during these previous tests.
    # note that "first_pack" is the first packet that will be sent, so it has to have the lowest time (we let python double-check this, just in case...)
    # Then either 'bug_pack' or 'good_pack' is sent, depending on the case you want to reproduce.
    # (we crafted 'good_pack' by setting the last bit to "1" in "first_pack", and it worked (no error seen for a good packet))
    first_pack = b'20190222T101447.978326000'
    bug_pack   = b'20190222T101451.504435000'
    good_pack  = b'20190222T101447.978326001'
    
    # checks that our double-checking test works:(this should raise an exception)
    #check_packs('20190101T000000.000000000', '20180101T000000.000000000')
    
    check_packs(first_pack.decode('utf-8'), bug_pack.decode('utf-8')) # check that the time corresponding to "first_pack" is indeed the smallest time.
    check_packs(first_pack.decode('utf-8'), good_pack.decode('utf-8'))
        
    send_packet(sock, first_pack)

    if trig_bug:
        # will trigger a '-DB late write' response on affected systems:
        send_packet(sock, bug_pack)
    else:
        # send a """good""" packet (good for boost):
        send_packet(sock, good_pack)
                
    sock.close()
    
    print("End of test.");

if __name__ == '__main__':
    main_fct();
```

**Comment by JoelStienlet** [comment]
I tried exactly the same in a VM running ubuntu 18.10 ( boost 1_67  gcc 8.2.0), and got the same result as under fedora 29.

**Comment by Lazin** [comment]
I started the script on Ubuntu 16.04 with Boost 1.58 and here is its output:

```
Test: send hand-crafted data to akumuli server
+test sensor=dummy
+20190222T101447.978326000
+1234

Packet sent.
socket error recv:  timed out
+test sensor=dummy
+20190222T101451.504435000
+1234

Packet sent.
socket error recv:  timed out
End of test.
```

Let me try this on ubuntu 18.10 (have to install it first). Probably, the bug can only be reproduced with newer Boost versions.

**Comment by JoelStienlet** [comment]
It's certainly a change they made recently in boost indeed. On ubuntu 18.10 and fedora29 I get (just copied the end of the output):
```
Packet sent.
reponse: (please also check Akumuli's logs)
b'-DB late write\r\n'
End of test.
```

**Comment by Lazin** [comment]
I've started the script in Ubuntu 18.10 and it hasn't detected the error:

```
Test: send hand-crafted data to akumuli server
+test sensor=dummy
+20190222T101447.978326000
+1234

Packet sent.
socket error recv:  timed out
+test sensor=dummy
+20190222T101451.504435000
+1234

Packet sent.
socket error recv:  timed out
End of test.
```

gcc --version
gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0

apt show libboost-all-dev 
Package: libboost-all-dev
Version: 1.67.0.0ubuntu1

I'll try it on Fedora. Can you describe how did you built it? Did any extra flags or definitions was used?

**Comment by JoelStienlet** [comment]
How I build & install it:
```
cd Akumuli
mkdir build
cmake ..
make -j7
sudo make install
```
How I run the server:
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64 akumulid`
Without changing whatsoever (fresh git clone) I get this bug, both on ubuntu 18.10 and fedora 29.
(my fedora is my dev machine, so It has miscellaneous libraries installed, but the ubuntu machine is a VM freshly installed only for the purpose of this test)

**Comment by JoelStienlet** [comment]
As a workaround I suggest to add this line to CMakeLists.txt:
`add_definitions(-DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG)`
I just tried it, and apparently it works with this modification. (by "it works" I mean, this bug disappears)
(I only get complaints from the compiler that the symbol is defined twice, but at least I get no error on runtime with this change)

**Comment by JoelStienlet** [comment]
I've a question: may boost use different code depending on the CPU's architecture? That may explain why you don't see this bug and I do.

**Comment by JoelStienlet** [comment]
If you want to see this bug by yourself I can create you an account on my VM, and you can send my your ssh publickey to j.stienlet@gmail.com (I just need to configure a DMZ to isolate the VM from my LAN). Finding the root cause of a bug that you can't even reproduce is like an herculean task...

**Comment by Lazin** [comment]
I was able to reproduce the bug using your feedback. I was building release version but the bug appears only in debug version. I'm going to use the fix you've provided. It looks like I've used this build option in a wrong way. The documentation says that you should add/remove it from your Jam file. Otherwise, code included in different translation units can be inconsistent. In this case the 64-bit ptime value was copied to the 96-bit ptime. 

The good thing is that CI tests can detect this bug. So all previously built packages are fine.

**Comment by JoelStienlet** [comment]
Good news that previously built packages are fine :).
I close the issue as your PR solves this bug. 
Thank you again for your help!
