### ISSUE TITLE
Next release branch

### ISSUE THREAD

**Issue by a615549958** [akumuli/Akumuli#298]
Hi, when will  release next  version?

**Comment by Lazin** [comment]
When it will be ready, I don't have a regular release schedule. Why are you asking?

**Comment by a615549958** [comment]
Last release version didn't include WAL, Ｉ need a Stable version which include WAL.  Which tests do I need to confirm that WAL is stable?

**Comment by Lazin** [comment]
Oh, you mean 'releases' on github? I drafted new release. It now contains WAL.
You can always check the 'master' branch if you need the latest code. It contains only stable changes.
