### ISSUE TITLE
Any TTL support/limitation?

### ISSUE THREAD

**Issue by sptrakesh** [akumuli/Akumuli#307]
Does Akumuli have any in-built TTL implementation?  In othe words, is old data automatically deleted after some period of time?  My current use case is I do not want any deletion, but still would like to know if there is any TTL support.

**Comment by Lazin** [comment]
There is no per-series TTL. Akumuli implements a pre-allocated storage pool that functions as a ring buffer. Old data is deleted when there is no space to store the new. So the retention is based on available disk space and not on actual life time. You can also configure infinitely growing storage that never deletes anything if you need that.

**Comment by sptrakesh** [comment]
Is there documentation for run time parameters and their meaning?  I am running via the docker image, and see some options listed.  Is the total data storage determined by `nvolumes * volume_size`?

**Comment by Lazin** [comment]
Yes, there is a documentation section - https://docs.akumuli.org/getting-started#configuring-akumuli it describes configuration parameters. There are also some explanations on docker hub - https://hub.docker.com/r/akumuli/akumuli/ It's mostly related to docker image. 
Total storage size is defined by `nvolumes * volume_size`.
