### ISSUE TITLE
Building Akumuli on Raspberry Pi 3

### ISSUE THREAD

**Issue by wjj7yj** [akumuli/Akumuli#309]
Hi Folks,

I try to build Akumuli on Raspberry Pi 3  of which the OS is raspbian/jessie, and have got this error:

/usr/include/c++/4.9/atomic:685:7: error: ‘constexpr’ does not name a type
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
       ^
/usr/include/c++/4.9/atomic:685:7: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.9/atomic:698:14: error: expected ‘;’ at end of member declaration
       atomic() noexcept = default;
              ^
/usr/include/c++/4.9/atomic:698:16: error: ‘noexcept’ does not name a type
       atomic() noexcept = default;

Is there any way to fix it?
Thanks.

**Comment by Lazin** [comment]
There is a repository with pre-built packages here - https://packagecloud.io/Lazin/Akumuli 
It has Ubuntu ARM64 packages that might be possible to install on raspbian/jessie (I'm not sure about that part).
What GCC version are you using?

**Comment by wjj7yj** [comment]
@Lazin gcc version 4.9.2 (Raspbian 4.9.2-10+deb8u1)

**Comment by Lazin** [comment]
You can try to replace -std=c++11 with -std=c++0x. GCC 4.9 should be able to build the code. It's not that old.

**Comment by wjj7yj** [comment]
@Lazin I found that options in CMAKE_CXX_FLAGS_RELEASE are not turn out when gcc compile source. So, I change CMAKE_CXX_FLAGS_RELEASE to CMAKE_CXX_FLAGS, the errors about "-std=c++11" disappeared. But there are still some other erros:
1. sign-compare: some function in cpp compared unsigned int and int. I fix it;
2. unsigned long int compared to unsigned int. I fix it;
3. left shift count >= width of type:  static const u64 a = (1ul << 32) - 1;
At last, I realized that Raspberry Pi 3 support 64bit but Raspbian is a 32bit OS. So, Akumuli can't run on Raspberry Pi 3 with raspbian/jessie 32bit OS! Am I rignt?

**Comment by Lazin** [comment]
Yes, you're right about 32-bit support. It is possible to fix all this issues and make it run on 32-bit CPU though. But it will require to fix a lot of issues like that. Maybe it's possible to use 64-bit OS on R-Pi?

**Comment by wjj7yj** [comment]
Currently, there is no officely supported 64-bit OS on Raspberry Pi 3, even on newest Pi 4.

**Comment by Lazin** [comment]
That depend on write volume and queries that you'll need to run. It's easier to use TSDB of any sort. I think Graphite may work on 32-bit systems.

**Comment by wjj7yj** [comment]
Thanks for your advice.
