### ISSUE TITLE
alternative .akumulid definition

### ISSUE THREAD

**Issue by igor-zacharov** [akumuli/Akumuli#313]

**Comment by igor-zacharov** [comment]
I would need the possibility to start akumulid with an alternative definition file.
Right now there is only one fixed path: /root/.akumulid
I propose an option for akumulid instance to read the path from the command line.
This is needed for multiple instances of akumulid to run simultaneously.

Thank you, Igor.

**Comment by Lazin** [comment]
I'll try to add this to the next PR
