### ISSUE TITLE
Error messages on installing/starting akumulid service

### ISSUE THREAD

**Issue by asteinarson** [akumuli/Akumuli#321]
My OS: OS Ubuntu 16.04 (Xenial).
I installed akumuli via PackageCloud (tried both 0.8.71 and 0.8.70).

On running: `$ akumulid --init` I get:
```
log4cxx: No appender could be found for logger (main).
log4cxx: Please initialize the log4cxx system properly.
OK configuration file created at: "/root/.akumulid"
```
Then later, on trying to start the daemon, i get: 
```
$ akumulid
FAILURE WAL.path doesn't exist
```
Any suggestion how to get my install working? Thanks.

**Comment by Lazin** [comment]
Hi,
You should create the database first by running `akumulid --create`.

**Comment by asteinarson** [comment]
It worked, thanks. I assumed the log4cxx warnings disabled daemon startup.
