### ISSUE TITLE
jemalloc usage

### ISSUE THREAD

**Issue by webfolderio** [akumuli/Akumuli#327]
Hi,

First of all thanks for such a great open source product/application.

I wrote a custom build script for Akumuli. All external libraries except **jemalloc** linked statically instead of shared library.
Although it's not fully tested, initial results are good. Akumuli works well without any error.
I would like to know if there is specific reason to use jemalloc instead of standard glibc allocator. Is it possible to akumulid with standard allocator?

I am not c/c++ developer but as far as i know it's used for performance reasons. Is it the same reason for your case?

Thanks

**Comment by Lazin** [comment]
Hi,
jemalloc is used only for performance reasons. So, it's absolutely safe to remove it. No jemalloc specific functionality was used anywhere in the code.

**Comment by webfolderio** [comment]
Thanks
