### ISSUE TITLE
Binding sever ip explicitly

### ISSUE THREAD

**Issue by webfolderio** [akumuli/Akumuli#329]
Hi,

Is there a configuration property to set IP?

There are two use cases;

1) there might be more than one ip assigned to server instance
2) there aren't any auth. mechanism for both tcp/udp and http protocol? if the installed sever connected to internet directly without firewall, thirdparty users might be insert and query random data easily.

thanks

**Comment by Lazin** [comment]
I'm working to add configuration option.
There is no way to add auth to tcp/udp right now. It's not supported on protocol level and the database doesn't have a notion of user or user group to start with. This endpoints are not supposed to be exposed to internet directly. A lot of harm could be done using this endponts by the 3rd party. 

You can expose http endpoint but I suggest to use the reverse proxy in this case. It can be used to add auth and ssl termination for your app.
