### ISSUE TITLE
Exception handling strategy

### ISSUE THREAD

**Issue by GeoffreyRobert** [akumuli/Akumuli#345]
Hello, I have a question regarding the way exceptions generated by libakumuli can be handled. Currently, in [libakumuli/util.h](https://github.com/akumuli/Akumuli/blob/master/libakumuli/util.h), we have:
<pre lang="c++">
/** Panic macro.
  * @param msg error message
  * @throws Exception.
  */
#define AKU_PANIC(msg) Akumuli::invoke_panic_handler(msg); throw 1;
</pre>
And in [libakumuli/util.cpp](https://github.com/akumuli/Akumuli/blob/master/libakumuli/util.cpp#L51-L56):
<pre lang="c++">
// coverity[+kill]
void invoke_panic_handler(const char* message) {
    (*g_panic_handler)(message);
    Logger::msg(AKU_LOG_ERROR, message);
    std::terminate();
}
</pre>

Why the call to ```std::terminate``` ? Why is it followed by a ```throw``` in ```AKU_PANIC``` ?
Correct me if I'm wrong but this prevents a library consumer to catch anything and I believe it can cause problems as it won't properly destroy existing objects.

**Comment by GeoffreyRobert** [comment]
Ok that makes sense, thanks for the answer.
I asked the question because I had some issues running unit tests from [`test_column_store`](https://github.com/akumuli/Akumuli/blob/master/unittests/test_column_store.cpp#L44-L49) and [test_storage](https://github.com/akumuli/Akumuli/blob/master/unittests/test_storage.cpp#L48-L53) that ended up aborted.
The termination originated back to the [`MetadataStorage`](https://github.com/akumuli/Akumuli/blob/master/libakumuli/metadatastorage.cpp#L62-L101) constructor, but with no hint other than SIGABORT was a bit hard to track.


Note for those with a similar issue : I used conan as dependency manager and the package recipe for `apache-apr-util` did not properly link to `sqlite3`. So when building you dependencies from source, you solve the issue by using:
```
./configure ... -with-sqlite3=/path/to/sqlite3/root/dir/ ...
```
With `root/dir/` being above `include/` and `lib/`.

**Comment by Lazin** [comment]
It's because of `apr-util-sqlite` library, it's loaded dynamically so all utils that generate dependencies don't work correctly. I solved this issue [for RPM](https://github.com/akumuli/Akumuli/blob/master/akumulid/CMakeLists.txt#L55) and [and dpkg](https://github.com/akumuli/Akumuli/blob/master/akumulid/CMakeLists.txt#L68).

**Comment by GeoffreyRobert** [comment]
Ok, thank you for your time.
