### ISSUE TITLE
Getting Started with libakumuli Wiki documentation

### ISSUE THREAD

**Issue by JaFenix** [akumuli/Akumuli#346]
Hello, I'm trying to use the Getting Started with libakumuli Wiki documentation but it appears that the C API functions have changed.  Is the Wiki document out of date?  Is there another example of how to use the libakumuli API?

**Comment by Lazin** [comment]
Hey,
Yes, the C interface have changed and "Getting Started" guide is outdated. The main difference is that you need to create a session object first. This object should be passed to query and write functions. You have to use a session per thread to have good performance.

You can find the example here - https://github.com/akumuli/Akumuli/blob/master/functests/storage_test.cpp.

**Comment by JaFenix** [comment]
Great, thank you!
