### ISSUE TITLE
Announcement: Akumuli Java Support

### ISSUE THREAD

**Issue by webfolderio** [akumuli/Akumuli#369]
Hi,

We released [tsdb4j](https://github.com/webfolderio/tsdb4j) which is a Java driver/client for libakumuli.
tsdb4j communicates with Akumuli (libakumuli) via JNI and neither use TCP, UDP or HTTP protocol.
It supports Linux (ubuntu, centos, alpine), macos and windows.
tsdb4j license under the Apache 2.0 license and suitable for open source and commercial projects.

**Comment by Lazin** [comment]
Great news!
