### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [akumuli/Akumuli#50]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [AKU_E…](https://github.com/akumuli/Akumuli/blob/f330214943f46ce98b88eac7adf3a17e824c3f3f/include/akumuli_def.h#L42)
* [AKU_LOG_…](https://github.com/akumuli/Akumuli/blob/31ad2b3a96586e061a2e81c608f5c1f75db584d2/include/akumuli_config.h#L32)

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/akumuli/Akumuli/commit/8e9457992c4026180315b9c5f4f7494823c0d1ed "Reuse of enumerations").

**Comment by elfring** [comment]
Would another enumeration make sense for [AKU_LOG values](https://github.com/akumuli/Akumuli/blob/31ad2b3a96586e061a2e81c608f5c1f75db584d2/include/akumuli_config.h#L32 "Log levels")?

**Comment by Lazin** [comment]
Yep. Forgot about them.

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/akumuli/Akumuli/commit/887d689acf0b2af0b327bee8d53cb05f45356c54 "Introduction of the aku_LogLevel enumeration").
