### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by KrishnaPG** [akumuli/Akumuli#56]
First of all - allow me to congratulate you for your efforts on this. This is very much appreciated and very much-in-need requirement for the big-data analytics industry today.

I have been looking for a good high-performance time-series databases. The best options today are OpenTSDB, InfluxDB or ElasticSearch.

The problem with them is: Both ES and OTSDB are monstrously huge (on resources), requiring you pull up java virtual machines and what not for their operation. InfluxDB is good on performance, low on resources (no dependencies), but no where near production grade.

This is where this project could make an impact. Low on resources, high on performance and production  grade is what is needed for big-data clusters to perform efficiently.

I am not sure how serious you are about this project (may be this is just a hobby project for you) - but if you are indeed committed to make this production grade, then would like to bring few points to your consideration to put things in perspective (on what is needed in the industry).

I see from your readme.md about writing performance of 1 million points. While it is good, just consider this below scenario:
*    Sampling one sensor every second for one year generates about 31.5 million points. Now it is not uncommon for a simple household to have anywhere between 5 to 10 sensors and for an industry to have anywhere between 100 to 500 sensors to monitor. So, you are essentially looking at  roughly about 3000 million data points per year (for an industrial scenario). 

The point I am trying to make is, if someone needs to import past 3 years data just for testing out few business scenarios, then they are looking at average of 9000 million data points to import. This is where much higher write performance is critical. (If import itself takes days, then querying back and analyzing them would become in-feasible).

It is not uncommon to draw interactive charts for past 3 to 5 years data. So, a performant database is expected to be able to return atleast 35 million points /second (one year worth data / second), to be able to remain responsive and fast enough for users. (Even that is slow, because imagine a chart loading for 5 seconds just to show 5 years data - not really good enough). 

This luxon [here](http://www.luxon.io/) has a nice interactive chart that is demonstrating "30-year second-by-second sensor data. A total of 1billion data-points". 

It would be great to see this project reaching that kind of performance.

**Comment by Lazin** [comment]
I think that this is a bit unrealistic. Compression algorithm in Akumuli can compress each data point (id, time-stamp, value) up to four and half bytes, actual compression ratio depends on data and many real world time-series will be compressed up 10 bytes per data point or so. This is a really good result anyway considering that id and time-stamp is a 64-bit integers and value is represented as 64-bit floating point number. Modern SSD can write data at speed about 100MB/s, this gives us write throughput upper bound for Akumuli at (100*1024*1024)B/s/10B = 10485760 data-points per second.

The same thinking is applicable for reads.
