### ISSUE TITLE
Akumuli and Python Pandas

### ISSUE THREAD

**Issue by femtotrader** [akumuli/Akumuli#80]
Hello,

I'm new to Akumuli.
Is there a way to use Akumuli with Python Pandas ?

Kind regards

**Comment by Lazin** [comment]
Hi,
Akumuli doesn't support pandas directly (there is no python package that integrates Akumuli with pandas). But it is quite easy to get data out of Akumuli in CSV format and push it into pandas data frame.

Sadly, documentation isn't ready yet. At the moment I'm testing Akumuli extensively. After that I'll start working on documentation. And when documentation will be completed - Akumuli will become ready for early adopters.
